name: Docker Build and Push

on:
  push:
    tags:
      - '*'

jobs:
  build:
    name: Build Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: docker build -t hastings2002/project_4 .

      - name: Extract tag information
        id: extract_tag
        uses: docker/metadata-action@v3
        with:
          images: hastings2002/project_4

      - name: Push Docker image to DockerHub
        run: |
          docker push hastings2002/project_4
          TAG="${{ steps.extract_tag.outputs.tags }}"
          if ! docker tag hastings2002/project_4 hastings2002/project_4:$TAG; then
            echo "Error: Docker tag failed"
            exit 1
          fi
          if ! docker push hastings2002/project_4:$TAG; then
            echo "Error: Docker push failed for tagged image"
            exit 1
          fi
          if [[ "$TAG" == *.*.* ]]; then
            docker tag hastings2002/project_4 hastings2002/project_4:latest
            if ! docker push hastings2002/project_4:latest; then
              echo "Error: Docker push failed for latest tag"
              exit 1
            fi
            MAJOR=$(echo $TAG | cut -d. -f1)
            docker tag hastings2002/project_4 hastings2002/project_4:$MAJOR
            if ! docker push hastings2002/project_4:$MAJOR; then
              echo "Error: Docker push failed for major tag"
              exit 1
            fi
            MAJOR_MINOR=$(echo $TAG | cut -d. -f1-2)
            docker tag hastings2002/project_4 hastings2002/project_4:$MAJOR_MINOR
            if ! docker push hastings2002/project_4:$MAJOR_MINOR; then
              echo "Error: Docker push failed for major.minor tag"
              exit 1
            fi
          fi
