name: Docker Build and Push

on:
  push:
    tags:
      - '*'

jobs:
  build:
    name: Build Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: docker build -t hastings2002/project_4 .

      - name: Extract tag information
        id: extract_tag
        uses: docker/metadata-action@v3

      - name: Push Docker image to DockerHub
        run: |
          docker push hastings2002/project_4
          TAG="${{ steps.extract_tag.outputs.tags }}"
          docker tag hastings2002/project_4 hastings2002/project_4:$TAG
          docker push hastings2002/project_4:$TAG
          if [[ "$TAG" == *.*.* ]]; then
            docker tag hastings2002/project_4 hastings2002/project_4:latest
            docker push hastings2002/project_4:latest
            MAJOR=$(echo $TAG | cut -d. -f1)
            docker tag hastings2002/project_4 hastings2002/project_4:$MAJOR
            docker push hastings2002/project_4:$MAJOR
            MAJOR_MINOR=$(echo $TAG | cut -d. -f1-2)
            docker tag hastings2002/project_4 hastings2002/project_4:$MAJOR_MINOR
            docker push hastings2002/project_4:$MAJOR_MINOR
          fi
