name: Docker Build and Push

on:
  push:
    tags:
      - '*'

jobs:
  build:
    name: Build Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: docker build -t hastings2002/project_4 .

      - name: Determine Git tag
        id: git_tag
        run: echo "::set-output name=tag::$(git describe --tags)"

      - name: Push Docker image to DockerHub
        run: |
          docker tag hastings2002/project_4:latest hastings2002/project_4:${{ steps.git_tag.outputs.tag }}
          docker push hastings2002/project_4:${{ steps.git_tag.outputs.tag }}
          docker push hastings2002/project_4:latest
